server {
  listen 3000;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location /nginx_status/ {
    access_log off;
    return 404;
  }

  location / {
    add_header Content-Security-Policy "frame-ancestors ${IFRAME_ALLOWED_ORIGIN}" always;
    try_files $uri $uri/ /index.html;
  }
}
